# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(871, 600)
        MainWindow.setStyleSheet("/* Main Application Styling */\n"
"QWidget {\n"
"    font-family: \"Segoe UI\", \"Arial\", sans-serif;\n"
"    font-size: 13px;\n"
"    color: #3a3a3a;\n"
"}\n"
"\n"
"/* Main Window Background */\n"
"QMainWindow {\n"
"    background-color: #f8f5ff;  /* Very light purple background */\n"
"}\n"
"\n"
"/* Toolbar Styling */\n"
"QToolBar {\n"
"    background-color: #e6e0ff;\n"
"    border: none;\n"
"    border-bottom: 1px solid #d5c8ff;\n"
"    padding: 4px;\n"
"    spacing: 6px;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 5px;\n"
"    padding: 5px 8px;\n"
"    color: #5a4d8a;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #d5c8ff;\n"
"    border: 1px solid #b8a3ff;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: #b8a3ff;\n"
"    color: white;\n"
"}\n"
"\n"
"QToolButton:checked {\n"
"    background-color: #9e86ff;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Menu Bar Styling */\n"
"QMenuBar {\n"
"    background-color: #f0ebff;\n"
"    border-bottom: 1px solid #d5c8ff;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    padding: 5px 12px;\n"
"    background-color: transparent;\n"
"    color: #5a4d8a;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #d5c8ff;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    color: #5a4d8a;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 6px 24px 6px 12px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #f0ebff;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: #e6e0ff;\n"
"    margin: 4px 8px;\n"
"}\n"
"\n"
"/* Status Bar Styling */\n"
"QStatusBar {\n"
"    background-color: #e6e0ff;\n"
"    color: #5a4d8a;\n"
"    border-top: 1px solid #d5c8ff;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"/* Push Buttons */\n"
"QPushButton {\n"
"    background-color: #e6e0ff;\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 6px;\n"
"    padding: 7px 14px;\n"
"    color: #5a4d8a;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #d5c8ff;\n"
"    border-color: #b8a3ff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #9e86ff;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #f0f0f0;\n"
"    color: #aaaaaa;\n"
"    border-color: #dddddd;\n"
"}\n"
"\n"
"/* Primary Action Button */\n"
"QPushButton[primary=\"true\"] {\n"
"    background-color: #9e86ff;\n"
"    border: 1px solid #8a6dff;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton[primary=\"true\"]:hover {\n"
"    background-color: #8a6dff;\n"
"}\n"
"\n"
"QPushButton[primary=\"true\"]:pressed {\n"
"    background-color: #7a5bef;\n"
"}\n"
"\n"
"/* Checkboxes and Radio Buttons */\n"
"QCheckBox, QRadioButton {\n"
"    color: #5a4d8a;\n"
"    spacing: 6px;\n"
"}\n"
"\n"
"QCheckBox::indicator, QRadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    border: 1px solid #b8a3ff;\n"
"    border-radius: 4px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #9e86ff;\n"
"    image: url(:/icons/check_white.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    border: 1px solid #b8a3ff;\n"
"    border-radius: 9px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #9e86ff;\n"
"    border: 5px solid white;\n"
"}\n"
"\n"
"/* Line Edits and Text Edits */\n"
"QLineEdit, QTextEdit, QPlainTextEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 6px;\n"
"    padding: 5px 5px;\n"
"    selection-background-color: #9e86ff;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus {\n"
"    border: 1px solid #9e86ff;\n"
"}\n"
"\n"
"/* Combo Boxes */\n"
"QComboBox {\n"
"    background-color: white;\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 6px;\n"
"    padding: 3px 5px;\n"
"    min-width: 6em;\n"
"    color: #5a4d8a;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #b8a3ff;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 24px;\n"
"    border-left: 1px solid #d5c8ff;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/down_arrow_purple.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 6px;\n"
"    padding: 6px 0;\n"
"    selection-background-color: #f0ebff;\n"
"    selection-color: #5a4d8a;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Sliders */\n"
"QSlider::groove:horizontal {\n"
"    height: 6px;\n"
"    background: #e6e0ff;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #9e86ff;\n"
"    width: 18px;\n"
"    margin: -6px 0;\n"
"    border-radius: 9px;\n"
"    border: 2px solid white;\n"
"}\n"
"\n"
"/* Progress Bars */\n"
"QProgressBar {\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 6px;\n"
"    text-align: center;\n"
"    background-color: white;\n"
"    color: #5a4d8a;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #9e86ff;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 8px;\n"
"    margin-top: 12px;\n"
"    padding-top: 20px;\n"
"    background-color: white;\n"
"    color: #5a4d8a;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 12px;\n"
"    padding: 0 6px;\n"
"    color: #7a5bef;\n"
"}\n"
"\n"
"/* Tab Widgets */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 8px;\n"
"    background: white;\n"
"    margin-top: 4px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #e6e0ff;\n"
"    border: 1px solid #d5c8ff;\n"
"    border-bottom: none;\n"
"    padding: 8px 16px;\n"
"    color: #5a4d8a;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    margin-right: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: white;\n"
"    color: #7a5bef;\n"
"    border-bottom: 1px solid white;\n"
"    margin-bottom: -1px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: #d5c8ff;\n"
"}\n"
"\n"
"/* Scroll Bars */\n"
"QScrollBar:vertical {\n"
"    background: #f0ebff;\n"
"    width: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #d5c8ff;\n"
"    min-height: 30px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #b8a3ff;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0;\n"
"    background: none;\n"
"}\n"
"\n"
"/* Table View Styling */\n"
"QTableView {\n"
"    gridline-color: #e6e0ff;\n"
"    background-color: white;\n"
"    alternate-background-color: #faf8ff;\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 5px;\n"
"    selection-background-color: #f0ebff;\n"
"    selection-color: #5a4d8a;\n"
"}\n"
"\n"
"QTableView QTableCornerButton::section {\n"
"    background-color: #f0ebff;\n"
"    border: 1px solid #d5c8ff;\n"
"    border-top-left-radius: 7px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0ebff;\n"
"    color: #5a4d8a;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-bottom: 1px solid #d5c8ff;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    background-color: #d5c8ff;\n"
"    color: #5a4d8a;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: #f0ebff;\n"
"}\n"
"\n"
"QTableView::item:hover {\n"
"    background-color: #f5f2ff;\n"
"}\n"
"\n"
"/* Tree View Styling */\n"
"QTreeView {\n"
"    background-color: white;\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 8px;\n"
"    alternate-background-color: #faf8ff;\n"
"    show-decoration-selected: 1;\n"
"}\n"
"\n"
"QTreeView::item {\n"
"    padding: 6px;\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"QTreeView::item:hover {\n"
"    background-color: #f5f2ff;\n"
"}\n"
"\n"
"QTreeView::item:selected {\n"
"    background-color: #f0ebff;\n"
"    color: #5a4d8a;\n"
"}\n"
"\n"
"QTreeView::branch {\n"
"    image: url(:/icons/branch_closed_purple.svg);\n"
"}\n"
"\n"
"QTreeView::branch:open {\n"
"    image: url(:/icons/branch_open_purple.svg);\n"
"}\n"
"\n"
"/* Splitter Styling */\n"
"QSplitter::handle {\n"
"    background-color: #e6e0ff;\n"
"    width: 6px;\n"
"    height: 6px;\n"
"}\n"
"\n"
"QSplitter::handle:hover {\n"
"    background-color: #d5c8ff;\n"
"}\n"
"\n"
"/* Dock Widget Styling */\n"
"QDockWidget {\n"
"    titlebar-close-icon: url(:/icons/close_purple.svg);\n"
"    titlebar-normal-icon: url(:/icons/float_purple.svg);\n"
"    background: white;\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QDockWidget::title {\n"
"    background: #f0ebff;\n"
"    padding: 8px;\n"
"    text-align: center;\n"
"    color: #5a4d8a;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"\n"
"/* Spin Boxes */\n"
"QSpinBox, QDoubleSpinBox {\n"
"    background-color: white;\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    color: #5a4d8a;\n"
"}\n"
"\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button {\n"
"    border-left: 1px solid #d5c8ff;\n"
"    border-bottom: 1px solid #d5c8ff;\n"
"    border-top-right-radius: 5px;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button {\n"
"    border-left: 1px solid #d5c8ff;\n"
"    border-bottom-right-radius: 5px;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QSpinBox::up-arrow, QDoubleSpinBox::up-arrow {\n"
"    image: url(:/icons/up_arrow_purple.svg);\n"
"}\n"
"\n"
"QSpinBox::down-arrow, QDoubleSpinBox::down-arrow {\n"
"    image: url(:/icons/down_arrow_purple.svg);\n"
"}\n"
"\n"
"/* Tooltips */\n"
"QToolTip {\n"
"    background-color: #ffffff;\n"
"    color: #5a4d8a;\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"/* QListView Styling - Purple Theme */\n"
"QListView {\n"
"    background-color: white;\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 8px;\n"
"    padding: 4px;\n"
"    outline: 0; /* Remove focus border */\n"
"    color: #5a4d8a;\n"
"    alternate-background-color: #faf8ff;\n"
"    show-decoration-selected: 1;\n"
"}\n"
"\n"
"/* List Items */\n"
"QListView::item {\n"
"    height: 32px;\n"
"    padding: 6px 12px;\n"
"    border-bottom: 1px solid #f0ebff;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background-color: #f5f2ff;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"    background-color: #f0ebff;\n"
"    color: #7a5bef;\n"
"    border-radius: 4px;\n"
"    border: none;\n"
"}\n"
"\n"
"QListView::item:selected:active {\n"
"    background-color: #e6e0ff;\n"
"}\n"
"\n"
"/* Disabled Items */\n"
"QListView::item:disabled {\n"
"    color: #b8a3ff;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Scrollbar (consistent with table view) */\n"
"QListView QScrollBar:vertical {\n"
"    background: #f0ebff;\n"
"    width: 12px;\n"
"    border-radius: 6px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QListView QScrollBar::handle:vertical {\n"
"    background: #d5c8ff;\n"
"    min-height: 30px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QListView QScrollBar::handle:vertical:hover {\n"
"    background: #b8a3ff;\n"
"}\n"
"\n"
"/* Special Cases */\n"
"QListView[iconMode=\"true\"]::item {\n"
"    padding: 8px;\n"
"    border-radius: 6px;\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"QListView[iconMode=\"true\"]::item:hover {\n"
"    background-color: #f5f2ff;\n"
"    border: 1px solid #e6e0ff;\n"
"}\n"
"\n"
"QListView[iconMode=\"true\"]::item:selected {\n"
"    background-color: #f0ebff;\n"
"    border: 1px solid #d5c8ff;\n"
"}\n"
"\n"
"/* Drag and Drop Visuals */\n"
"QListView::item[dragging=\"true\"] {\n"
"    background-color: #e6e0ff;\n"
"    border: 1px dashed #b8a3ff;\n"
"    color: #7a5bef;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.LogInPage = QtWidgets.QWidget()
        self.LogInPage.setObjectName("LogInPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.LogInPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(280, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self.LogInPage)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 216, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.companyList = QtWidgets.QComboBox(self.frame)
        self.companyList.setMaximumSize(QtCore.QSize(250, 16777215))
        self.companyList.setObjectName("companyList")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.companyList)
        self.LogInPass = QtWidgets.QLineEdit(self.frame)
        self.LogInPass.setMaximumSize(QtCore.QSize(250, 16777215))
        self.LogInPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LogInPass.setClearButtonEnabled(False)
        self.LogInPass.setObjectName("LogInPass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.LogInPass)
        self.createBtn = QtWidgets.QPushButton(self.frame)
        self.createBtn.setMinimumSize(QtCore.QSize(110, 0))
        self.createBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.createBtn.setObjectName("createBtn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.createBtn)
        self.LogInBtn = QtWidgets.QPushButton(self.frame)
        self.LogInBtn.setMinimumSize(QtCore.QSize(110, 0))
        self.LogInBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LogInBtn.setObjectName("LogInBtn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LogInBtn)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 215, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.frame_2)
        spacerItem3 = QtWidgets.QSpacerItem(280, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.LogInPage)
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setObjectName("MainPage")
        self.formLayout_6 = QtWidgets.QFormLayout(self.MainPage)
        self.formLayout_6.setObjectName("formLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.MainPage)
        self.frame_4.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cNameData = QtWidgets.QLabel(self.frame_4)
        self.cNameData.setTextFormat(QtCore.Qt.PlainText)
        self.cNameData.setObjectName("cNameData")
        self.verticalLayout_3.addWidget(self.cNameData, 0, QtCore.Qt.AlignHCenter)
        self.line = QtWidgets.QFrame(self.frame_4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.dashboardBtn = QtWidgets.QPushButton(self.frame_4)
        self.dashboardBtn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.dashboardBtn.setFont(font)
        self.dashboardBtn.setCheckable(True)
        self.dashboardBtn.setChecked(False)
        self.dashboardBtn.setFlat(True)
        self.dashboardBtn.setObjectName("dashboardBtn")
        self.verticalLayout_3.addWidget(self.dashboardBtn)
        self.invoiceBtn = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.invoiceBtn.setFont(font)
        self.invoiceBtn.setCheckable(True)
        self.invoiceBtn.setFlat(True)
        self.invoiceBtn.setObjectName("invoiceBtn")
        self.verticalLayout_3.addWidget(self.invoiceBtn)
        self.inventoryBtn = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.inventoryBtn.setFont(font)
        self.inventoryBtn.setCheckable(True)
        self.inventoryBtn.setFlat(True)
        self.inventoryBtn.setObjectName("inventoryBtn")
        self.verticalLayout_3.addWidget(self.inventoryBtn)
        self.accountSetupBtn = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.accountSetupBtn.setFont(font)
        self.accountSetupBtn.setCheckable(False)
        self.accountSetupBtn.setDefault(False)
        self.accountSetupBtn.setFlat(True)
        self.accountSetupBtn.setObjectName("accountSetupBtn")
        self.verticalLayout_3.addWidget(self.accountSetupBtn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 386, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.line_2 = QtWidgets.QFrame(self.frame_4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.logOutBtn = QtWidgets.QPushButton(self.frame_4)
        self.logOutBtn.setObjectName("logOutBtn")
        self.verticalLayout_3.addWidget(self.logOutBtn)
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.MainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.dashboardP = QtWidgets.QWidget()
        self.dashboardP.setObjectName("dashboardP")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.dashboardP)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.salesChart = QtWidgets.QFrame(self.dashboardP)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.salesChart.sizePolicy().hasHeightForWidth())
        self.salesChart.setSizePolicy(sizePolicy)
        self.salesChart.setMinimumSize(QtCore.QSize(0, 300))
        self.salesChart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.salesChart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.salesChart.setObjectName("salesChart")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.salesChart)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.plot_sales = QtWidgets.QFrame(self.salesChart)
        self.plot_sales.setStyleSheet("QFrame {\n"
"    border: 1px solid #d5c8ff;\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.plot_sales.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plot_sales.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_sales.setObjectName("plot_sales")
        self.horizontalLayout_9.addWidget(self.plot_sales)
        self.frame_17 = QtWidgets.QFrame(self.salesChart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_59 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_7.addWidget(self.label_59)
        self.expiringLst = QtWidgets.QListView(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expiringLst.sizePolicy().hasHeightForWidth())
        self.expiringLst.setSizePolicy(sizePolicy)
        self.expiringLst.setObjectName("expiringLst")
        self.verticalLayout_7.addWidget(self.expiringLst)
        self.horizontalLayout_9.addWidget(self.frame_17, 0, QtCore.Qt.AlignRight)
        self.gridLayout_7.addWidget(self.salesChart, 4, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.dashboardP)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_7.addWidget(self.line_6, 1, 0, 1, 1)
        self.recentInv = QtWidgets.QTableView(self.dashboardP)
        self.recentInv.setObjectName("recentInv")
        self.gridLayout_7.addWidget(self.recentInv, 5, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.dashboardP)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_7.addWidget(self.line_5, 3, 0, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.dashboardP)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_50 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_6.addWidget(self.label_50, 0, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_6.addWidget(self.label_51, 0, 4, 1, 1)
        self.totalQtyD = QtWidgets.QLabel(self.frame_14)
        self.totalQtyD.setObjectName("totalQtyD")
        self.gridLayout_6.addWidget(self.totalQtyD, 0, 3, 1, 1)
        self.outD = QtWidgets.QLabel(self.frame_14)
        self.outD.setObjectName("outD")
        self.gridLayout_6.addWidget(self.outD, 0, 5, 1, 1)
        self.totalProdD = QtWidgets.QLabel(self.frame_14)
        self.totalProdD.setObjectName("totalProdD")
        self.gridLayout_6.addWidget(self.totalProdD, 0, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_6.addWidget(self.label_49, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_14, 2, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.dashboardP)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_64 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_5.addWidget(self.label_64)
        self.gridLayout_7.addWidget(self.frame_15, 0, 0, 1, 1)
        self.topProd = QtWidgets.QListView(self.dashboardP)
        self.topProd.setObjectName("topProd")
        self.gridLayout_7.addWidget(self.topProd, 1, 1, 5, 1, QtCore.Qt.AlignRight)
        self.label_58 = QtWidgets.QLabel(self.dashboardP)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_7.addWidget(self.label_58, 0, 1, 1, 1)
        self.stackedWidget_2.addWidget(self.dashboardP)
        self.invoiceP = QtWidgets.QWidget()
        self.invoiceP.setObjectName("invoiceP")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.invoiceP)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_9 = QtWidgets.QFrame(self.invoiceP)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(297, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 1, 1, 1)
        self.InvoiceNumber = QtWidgets.QLineEdit(self.frame_9)
        self.InvoiceNumber.setMaximumSize(QtCore.QSize(150, 16777215))
        self.InvoiceNumber.setObjectName("InvoiceNumber")
        self.gridLayout_3.addWidget(self.InvoiceNumber, 0, 3, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.frame_9)
        self.label_42.setObjectName("label_42")
        self.gridLayout_3.addWidget(self.label_42, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_9)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.frame_9)
        self.label_43.setObjectName("label_43")
        self.gridLayout_3.addWidget(self.label_43, 1, 2, 1, 1)
        self.InvoiceDate = QtWidgets.QDateEdit(self.frame_9)
        self.InvoiceDate.setMaximumSize(QtCore.QSize(150, 16777215))
        self.InvoiceDate.setCalendarPopup(True)
        self.InvoiceDate.setCurrentSectionIndex(0)
        self.InvoiceDate.setObjectName("InvoiceDate")
        self.gridLayout_3.addWidget(self.InvoiceDate, 1, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.InvoiceItemTable = QtWidgets.QTableView(self.invoiceP)
        self.InvoiceItemTable.setObjectName("InvoiceItemTable")
        self.verticalLayout_6.addWidget(self.InvoiceItemTable)
        self.frame_12 = QtWidgets.QFrame(self.invoiceP)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_5.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.discountV = QtWidgets.QLineEdit(self.frame_13)
        self.discountV.setObjectName("discountV")
        self.gridLayout_4.addWidget(self.discountV, 1, 5, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.frame_13)
        self.label_44.setObjectName("label_44")
        self.gridLayout_4.addWidget(self.label_44, 0, 0, 1, 1)
        self.cgstV = QtWidgets.QLineEdit(self.frame_13)
        self.cgstV.setObjectName("cgstV")
        self.gridLayout_4.addWidget(self.cgstV, 0, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.frame_13)
        self.label_45.setObjectName("label_45")
        self.gridLayout_4.addWidget(self.label_45, 0, 2, 1, 1)
        self.sgstV = QtWidgets.QLineEdit(self.frame_13)
        self.sgstV.setObjectName("sgstV")
        self.gridLayout_4.addWidget(self.sgstV, 0, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.frame_13)
        self.label_46.setObjectName("label_46")
        self.gridLayout_4.addWidget(self.label_46, 0, 4, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.frame_13)
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.label_47, 1, 4, 1, 1)
        self.grandtotalV = QtWidgets.QLineEdit(self.frame_13)
        self.grandtotalV.setObjectName("grandtotalV")
        self.gridLayout_4.addWidget(self.grandtotalV, 3, 5, 1, 1)
        self.grossV = QtWidgets.QLineEdit(self.frame_13)
        self.grossV.setObjectName("grossV")
        self.gridLayout_4.addWidget(self.grossV, 0, 5, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.frame_13)
        self.label_48.setObjectName("label_48")
        self.gridLayout_4.addWidget(self.label_48, 3, 4, 1, 1)
        self.schmD = QtWidgets.QLineEdit(self.frame_13)
        self.schmD.setObjectName("schmD")
        self.gridLayout_4.addWidget(self.schmD, 2, 5, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.frame_13)
        self.label_60.setObjectName("label_60")
        self.gridLayout_4.addWidget(self.label_60, 2, 4, 1, 1)
        self.gridLayout_5.addWidget(self.frame_13, 0, 2, 2, 1)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 1, 1, 1, 1)
        self.deleteItem = QtWidgets.QPushButton(self.frame_12)
        self.deleteItem.setMaximumSize(QtCore.QSize(70, 16777215))
        self.deleteItem.setObjectName("deleteItem")
        self.gridLayout_5.addWidget(self.deleteItem, 0, 0, 1, 1)
        self.noteE = QtWidgets.QLineEdit(self.frame_12)
        self.noteE.setMinimumSize(QtCore.QSize(200, 0))
        self.noteE.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.noteE.setText("")
        self.noteE.setObjectName("noteE")
        self.gridLayout_5.addWidget(self.noteE, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(self.invoiceP)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.productInput = QtWidgets.QComboBox(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productInput.sizePolicy().hasHeightForWidth())
        self.productInput.setSizePolicy(sizePolicy)
        self.productInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.productInput.setEditable(True)
        self.productInput.setCurrentText("")
        self.productInput.setObjectName("productInput")
        self.horizontalLayout_8.addWidget(self.productInput)
        self.addPBtn = QtWidgets.QPushButton(self.frame_11)
        self.addPBtn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.addPBtn.setObjectName("addPBtn")
        self.horizontalLayout_8.addWidget(self.addPBtn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.invoiceP)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.printInvoice = QtWidgets.QPushButton(self.frame_10)
        self.printInvoice.setObjectName("printInvoice")
        self.horizontalLayout_6.addWidget(self.printInvoice, 0, QtCore.Qt.AlignRight)
        spacerItem7 = QtWidgets.QSpacerItem(288, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.cancelInvoice = QtWidgets.QPushButton(self.frame_10)
        self.cancelInvoice.setObjectName("cancelInvoice")
        self.horizontalLayout_6.addWidget(self.cancelInvoice, 0, QtCore.Qt.AlignLeft)
        self.SaveInvoice = QtWidgets.QPushButton(self.frame_10)
        self.SaveInvoice.setObjectName("SaveInvoice")
        self.horizontalLayout_6.addWidget(self.SaveInvoice, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_6.addWidget(self.frame_10)
        self.stackedWidget_2.addWidget(self.invoiceP)
        self.inventoryP = QtWidgets.QWidget()
        self.inventoryP.setObjectName("inventoryP")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.inventoryP)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_21 = QtWidgets.QLabel(self.inventoryP)
        self.label_21.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.line_4 = QtWidgets.QFrame(self.inventoryP)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.frame_8 = QtWidgets.QFrame(self.inventoryP)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_52 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_7.addWidget(self.label_52)
        self.totalData = QtWidgets.QLabel(self.frame_8)
        self.totalData.setObjectName("totalData")
        self.horizontalLayout_7.addWidget(self.totalData)
        self.label_53 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_7.addWidget(self.label_53)
        self.totalQtyInv = QtWidgets.QLabel(self.frame_8)
        self.totalQtyInv.setObjectName("totalQtyInv")
        self.horizontalLayout_7.addWidget(self.totalQtyInv)
        self.label_54 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_7.addWidget(self.label_54)
        self.totalValueInv = QtWidgets.QLabel(self.frame_8)
        self.totalValueInv.setObjectName("totalValueInv")
        self.horizontalLayout_7.addWidget(self.totalValueInv)
        self.label_55 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_7.addWidget(self.label_55)
        self.totalOutInv = QtWidgets.QLabel(self.frame_8)
        self.totalOutInv.setObjectName("totalOutInv")
        self.horizontalLayout_7.addWidget(self.totalOutInv)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.line_3 = QtWidgets.QFrame(self.inventoryP)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.frame_7 = QtWidgets.QFrame(self.inventoryP)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stockEntry_2 = QtWidgets.QGroupBox(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockEntry_2.sizePolicy().hasHeightForWidth())
        self.stockEntry_2.setSizePolicy(sizePolicy)
        self.stockEntry_2.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.stockEntry_2.setFont(font)
        self.stockEntry_2.setObjectName("stockEntry_2")
        self.formLayout_5 = QtWidgets.QFormLayout(self.stockEntry_2)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_32 = QtWidgets.QLabel(self.stockEntry_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.nameE = QtWidgets.QLineEdit(self.stockEntry_2)
        self.nameE.setObjectName("nameE")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameE)
        self.label_33 = QtWidgets.QLabel(self.stockEntry_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.qtyE = QtWidgets.QLineEdit(self.stockEntry_2)
        self.qtyE.setObjectName("qtyE")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.qtyE)
        self.label_34 = QtWidgets.QLabel(self.stockEntry_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.packE = QtWidgets.QLineEdit(self.stockEntry_2)
        self.packE.setObjectName("packE")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.packE)
        self.label_35 = QtWidgets.QLabel(self.stockEntry_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.hsnE = QtWidgets.QLineEdit(self.stockEntry_2)
        self.hsnE.setObjectName("hsnE")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.hsnE)
        self.label_36 = QtWidgets.QLabel(self.stockEntry_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.mfgE = QtWidgets.QLineEdit(self.stockEntry_2)
        self.mfgE.setObjectName("mfgE")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mfgE)
        self.label_37 = QtWidgets.QLabel(self.stockEntry_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.batchE = QtWidgets.QLineEdit(self.stockEntry_2)
        self.batchE.setObjectName("batchE")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.batchE)
        self.label_38 = QtWidgets.QLabel(self.stockEntry_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.expiryE = QtWidgets.QDateEdit(self.stockEntry_2)
        self.expiryE.setProperty("showGroupSeparator", False)
        self.expiryE.setDateTime(QtCore.QDateTime(QtCore.QDate(2027, 1, 1), QtCore.QTime(0, 0, 0)))
        self.expiryE.setCalendarPopup(True)
        self.expiryE.setTimeSpec(QtCore.Qt.LocalTime)
        self.expiryE.setDate(QtCore.QDate(2027, 1, 1))
        self.expiryE.setObjectName("expiryE")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.expiryE)
        self.label_39 = QtWidgets.QLabel(self.stockEntry_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.mrpE = QtWidgets.QLineEdit(self.stockEntry_2)
        self.mrpE.setObjectName("mrpE")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.mrpE)
        self.label_40 = QtWidgets.QLabel(self.stockEntry_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.rateE = QtWidgets.QLineEdit(self.stockEntry_2)
        self.rateE.setObjectName("rateE")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.rateE)
        self.label_57 = QtWidgets.QLabel(self.stockEntry_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_57)
        self.schE = QtWidgets.QLineEdit(self.stockEntry_2)
        self.schE.setObjectName("schE")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.schE)
        self.label_41 = QtWidgets.QLabel(self.stockEntry_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.gstE = QtWidgets.QLineEdit(self.stockEntry_2)
        self.gstE.setObjectName("gstE")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.gstE)
        self.clearEBtn = QtWidgets.QPushButton(self.stockEntry_2)
        self.clearEBtn.setObjectName("clearEBtn")
        self.formLayout_5.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.clearEBtn)
        self.addInvBtn = QtWidgets.QPushButton(self.stockEntry_2)
        self.addInvBtn.setObjectName("addInvBtn")
        self.formLayout_5.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.addInvBtn)
        self.gridLayout_2.addWidget(self.stockEntry_2, 0, 0, 2, 1)
        self.StockItems = QtWidgets.QTableView(self.frame_7)
        self.StockItems.setObjectName("StockItems")
        self.gridLayout_2.addWidget(self.StockItems, 1, 1, 1, 2)
        self.searchBtn = QtWidgets.QPushButton(self.frame_7)
        self.searchBtn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.searchBtn.setObjectName("searchBtn")
        self.gridLayout_2.addWidget(self.searchBtn, 0, 2, 1, 1)
        self.searchE = QtWidgets.QLineEdit(self.frame_7)
        self.searchE.setObjectName("searchE")
        self.gridLayout_2.addWidget(self.searchE, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.stackedWidget_2.addWidget(self.inventoryP)
        self.verticalLayout_4.addWidget(self.stackedWidget_2)
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frame_6)
        self.stackedWidget.addWidget(self.MainPage)
        self.CompanyPage = QtWidgets.QWidget()
        self.CompanyPage.setObjectName("CompanyPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.CompanyPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.CompanyPage)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.scrollArea = QtWidgets.QScrollArea(self.CompanyPage)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 821, 492))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cNameInp = QtWidgets.QLineEdit(self.groupBox)
        self.cNameInp.setObjectName("cNameInp")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cNameInp)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cAdd1Inp = QtWidgets.QLineEdit(self.groupBox)
        self.cAdd1Inp.setObjectName("cAdd1Inp")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cAdd1Inp)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cAdd2Inp = QtWidgets.QLineEdit(self.groupBox)
        self.cAdd2Inp.setObjectName("cAdd2Inp")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cAdd2Inp)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cCityInp = QtWidgets.QLineEdit(self.groupBox)
        self.cCityInp.setObjectName("cCityInp")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cCityInp)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cStateInp = QtWidgets.QLineEdit(self.groupBox)
        self.cStateInp.setObjectName("cStateInp")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cStateInp)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cPinInp = QtWidgets.QLineEdit(self.groupBox)
        self.cPinInp.setObjectName("cPinInp")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cPinInp)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cPhoneInp = QtWidgets.QLineEdit(self.groupBox)
        self.cPhoneInp.setObjectName("cPhoneInp")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cPhoneInp)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.cMailInp = QtWidgets.QLineEdit(self.groupBox)
        self.cMailInp.setObjectName("cMailInp")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cMailInp)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.cDLInp = QtWidgets.QLineEdit(self.groupBox_2)
        self.cDLInp.setText("")
        self.cDLInp.setObjectName("cDLInp")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cDLInp)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.cGSTInp = QtWidgets.QLineEdit(self.groupBox_2)
        self.cGSTInp.setText("")
        self.cGSTInp.setObjectName("cGSTInp")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cGSTInp)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cPanInp = QtWidgets.QLineEdit(self.groupBox_2)
        self.cPanInp.setText("")
        self.cPanInp.setObjectName("cPanInp")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cPanInp)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cRegNameInp = QtWidgets.QLineEdit(self.groupBox_2)
        self.cRegNameInp.setText("")
        self.cRegNameInp.setObjectName("cRegNameInp")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cRegNameInp)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.cBankNameInp = QtWidgets.QLineEdit(self.groupBox_2)
        self.cBankNameInp.setText("")
        self.cBankNameInp.setObjectName("cBankNameInp")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cBankNameInp)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.cAccNoInp = QtWidgets.QLineEdit(self.groupBox_2)
        self.cAccNoInp.setText("")
        self.cAccNoInp.setObjectName("cAccNoInp")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cAccNoInp)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.cIFSCInp = QtWidgets.QLineEdit(self.groupBox_2)
        self.cIFSCInp.setText("")
        self.cIFSCInp.setObjectName("cIFSCInp")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cIFSCInp)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.cBranchInp = QtWidgets.QLineEdit(self.groupBox_2)
        self.cBranchInp.setObjectName("cBranchInp")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cBranchInp)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.cPassInp = QtWidgets.QLineEdit(self.groupBox_3)
        self.cPassInp.setObjectName("cPassInp")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cPassInp)
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.cPassCInp = QtWidgets.QLineEdit(self.groupBox_3)
        self.cPassCInp.setObjectName("cPassCInp")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cPassCInp)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.frame_5 = QtWidgets.QFrame(self.CompanyPage)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(584, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.createCancelBtn = QtWidgets.QPushButton(self.frame_5)
        self.createCancelBtn.setObjectName("createCancelBtn")
        self.horizontalLayout_3.addWidget(self.createCancelBtn, 0, QtCore.Qt.AlignRight)
        self.createSaveBtn = QtWidgets.QPushButton(self.frame_5)
        self.createSaveBtn.setObjectName("createSaveBtn")
        self.horizontalLayout_3.addWidget(self.createSaveBtn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.CompanyPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.createBtn.setText(_translate("MainWindow", "Create"))
        self.LogInBtn.setText(_translate("MainWindow", "Log In"))
        self.cNameData.setText(_translate("MainWindow", "Company Name"))
        self.dashboardBtn.setText(_translate("MainWindow", "Dashboard"))
        self.invoiceBtn.setText(_translate("MainWindow", "Invoice"))
        self.inventoryBtn.setText(_translate("MainWindow", "Inventory"))
        self.accountSetupBtn.setText(_translate("MainWindow", "Account Setup"))
        self.logOutBtn.setText(_translate("MainWindow", "Log Out"))
        self.label_59.setText(_translate("MainWindow", "Expiring Products"))
        self.label_50.setText(_translate("MainWindow", "Total Quantity:"))
        self.label_51.setText(_translate("MainWindow", "Out Of Stock:"))
        self.totalQtyD.setText(_translate("MainWindow", "N/A"))
        self.outD.setText(_translate("MainWindow", "N/A"))
        self.totalProdD.setText(_translate("MainWindow", "N/A"))
        self.label_49.setText(_translate("MainWindow", "Total Product:"))
        self.label_64.setText(_translate("MainWindow", "Dashboard"))
        self.label_58.setText(_translate("MainWindow", "Top Products"))
        self.label_42.setText(_translate("MainWindow", "Invoice Number:"))
        self.label_20.setText(_translate("MainWindow", "Create Invoice"))
        self.label_43.setText(_translate("MainWindow", "Date:"))
        self.InvoiceDate.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.discountV.setText(_translate("MainWindow", "0.00"))
        self.label_44.setText(_translate("MainWindow", "SGST"))
        self.cgstV.setText(_translate("MainWindow", "0.00"))
        self.label_45.setText(_translate("MainWindow", "CGST"))
        self.sgstV.setText(_translate("MainWindow", "0.00"))
        self.label_46.setText(_translate("MainWindow", "Gross Amount"))
        self.label_47.setText(_translate("MainWindow", "Less Amount"))
        self.grandtotalV.setText(_translate("MainWindow", "0.00"))
        self.grossV.setText(_translate("MainWindow", "0.00"))
        self.label_48.setText(_translate("MainWindow", "Grand Total"))
        self.schmD.setText(_translate("MainWindow", "0.00"))
        self.label_60.setText(_translate("MainWindow", "Schm Discount"))
        self.deleteItem.setText(_translate("MainWindow", "Delete"))
        self.noteE.setPlaceholderText(_translate("MainWindow", "Note:"))
        self.addPBtn.setText(_translate("MainWindow", "Add"))
        self.printInvoice.setText(_translate("MainWindow", "Print"))
        self.cancelInvoice.setText(_translate("MainWindow", "Cancel"))
        self.SaveInvoice.setText(_translate("MainWindow", "Save"))
        self.label_21.setText(_translate("MainWindow", "Inventory"))
        self.label_52.setText(_translate("MainWindow", "Total Products: "))
        self.totalData.setText(_translate("MainWindow", "N/A"))
        self.label_53.setText(_translate("MainWindow", "Total Quantity:"))
        self.totalQtyInv.setText(_translate("MainWindow", "N/A"))
        self.label_54.setText(_translate("MainWindow", "Stock Value:"))
        self.totalValueInv.setText(_translate("MainWindow", "N/A"))
        self.label_55.setText(_translate("MainWindow", "Out of Stock"))
        self.totalOutInv.setText(_translate("MainWindow", "N/A"))
        self.stockEntry_2.setTitle(_translate("MainWindow", "Stock Entry"))
        self.label_32.setText(_translate("MainWindow", "Name:"))
        self.label_33.setText(_translate("MainWindow", "Quantity:"))
        self.label_34.setText(_translate("MainWindow", "Pack:"))
        self.label_35.setText(_translate("MainWindow", "HSN:"))
        self.label_36.setText(_translate("MainWindow", "MFG By:"))
        self.label_37.setText(_translate("MainWindow", "Batch:"))
        self.label_38.setText(_translate("MainWindow", "Expiry:"))
        self.expiryE.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_39.setText(_translate("MainWindow", "MRP:"))
        self.label_40.setText(_translate("MainWindow", "Rate:"))
        self.label_57.setText(_translate("MainWindow", "SCH:"))
        self.label_41.setText(_translate("MainWindow", "GST:"))
        self.gstE.setPlaceholderText(_translate("MainWindow", "Enter Value in Whole Number"))
        self.clearEBtn.setText(_translate("MainWindow", "Clear"))
        self.addInvBtn.setText(_translate("MainWindow", "Add To Inventory >>"))
        self.searchBtn.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Pharmacy Details"))
        self.groupBox.setTitle(_translate("MainWindow", "Basic Info"))
        self.label_2.setText(_translate("MainWindow", "Pharmacy Name:"))
        self.label_3.setText(_translate("MainWindow", "Address Line 1:"))
        self.label_4.setText(_translate("MainWindow", "Address Line 2:"))
        self.label_5.setText(_translate("MainWindow", "City:"))
        self.label_6.setText(_translate("MainWindow", "State:"))
        self.label_7.setText(_translate("MainWindow", "Pin Code:"))
        self.label_8.setText(_translate("MainWindow", "Phone:"))
        self.label_9.setText(_translate("MainWindow", "E-mail:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Financial Details"))
        self.label_10.setText(_translate("MainWindow", "DL Number:"))
        self.label_11.setText(_translate("MainWindow", "GST Number:"))
        self.label_12.setText(_translate("MainWindow", "PAN Number:"))
        self.label_13.setText(_translate("MainWindow", "Registard Name:"))
        self.label_14.setText(_translate("MainWindow", "Bank Name:"))
        self.label_15.setText(_translate("MainWindow", "A/C Number:"))
        self.label_16.setText(_translate("MainWindow", "IFSC Code:"))
        self.label_17.setText(_translate("MainWindow", "Branch:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Credentials"))
        self.label_18.setText(_translate("MainWindow", "Password:"))
        self.label_19.setText(_translate("MainWindow", "Confirm:"))
        self.createCancelBtn.setText(_translate("MainWindow", "Cancel"))
        self.createSaveBtn.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
